import './globals.css'
import Contexts from './contexts'
import ScrollProgressBar from '@atoms/ScrollProgressBar'
import Intro from '@organisms/Intro'

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="viewport" content="width=device-width" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <div className="background-gradient relative overflow-hidden bg-black">
                    <Contexts>
                        <Intro />
                        <ScrollProgressBar />
                        {children}
                    </Contexts>
                </div>
            </body>
        </html>
    )
}
